version: "3"

vars:
  K8s_VERSION: 1.30.0

tasks:
  docs:
    cmds:
      - helm-docs --template-files=./_templates.gotmpl --template-files=./_chart-readme.md.gotmpl

  deps-*:
    vars:
      CHART: "{{index .MATCH 0}}"
    cmds:
      - helm dependency update ./charts/{{.CHART}}

  template-*:
    vars:
      CHART: "{{index .MATCH 0}}"
    cmds:
      - helm template --kube-version {{.K8s_VERSION}} {{.CHART}} ./charts/{{.CHART}} {{.CLI_ARGS}}

  kubeconform-*:
    vars:
      CHART: "{{index .MATCH 0}}"
    cmds:
      - helm template --kube-version {{.K8s_VERSION}} {{.CHART}} ./charts/{{.CHART}} --values ./charts/{{.CHART}}/ci/kubeconform.yaml | kubeconform --kubernetes-version {{.K8s_VERSION}} --schema-location default --schema-location {{`'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'`}} --strict --summary
# yq e '[.. | select(has("image")) | .image]' .\charts\node-config\values.yaml
