name: Scorecard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 1 * * 6'

permissions: read-all

jobs:
  workflow:
    name: Reusable Workflow
    uses: action-stars/generic-workflows/.github/workflows/scorecard.yaml@0cddebf99588cb4c3e116dd5b7a7b0368757a435 # v0.3.0
    permissions:
      id-token: write
      security-events: write
    with:
      retention_days: 7
