name: Scorecard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 1 * * 6'

permissions: read-all

jobs:
  scorecard:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          persist-credentials: false

      - name: Run scorecard
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_format: sarif
          results_file: scorecard.sarif
          publish_results: true

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@cdcdbb579706841c47f7063dda365e292e5cad7a # v2.16.4
        with:
          sarif_file: scorecard.sarif

      - name: Upload artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: scorecard
          path: scorecard.sarif
          retention-days: 7
