name: Scorecard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '30 1 * * 6'

permissions: read-all

jobs:
  workflow:
    name: Reusable Workflow
    uses: action-stars/generic-workflows/.github/workflows/scorecard.yaml@e3af7631344637e477945f90849c85927d90f049 # v0.3.0
    permissions:
      id-token: write
      security-events: write
    with:
      retention_days: 7
