name: Validate PR

on:
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - charts/**

permissions: read-all

# curl -s https://endoflife.date/api/kubernetes.json | jq -r '[sort_by(.releaseDate) | reverse | .[0:4] | .[].latest] | join(",")'

jobs:
  workflow:
    name: Reusable Workflow
    uses: action-stars/helm-workflows/.github/workflows/validate.yaml@6e96761580e296e3b66097a518de397eff1c433c # v0.6.1
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    with:
      chart_dir: charts
      target_branch: main
      helm_docs: true
      helm_docs_args: --template-files=./_templates.gotmpl --template-files=./_chart-readme.md.gotmpl
      changelog: true
      ah_lint: true
      kubeconform: true
      kubeconform_k8s_versions: ${{ vars.K8S_VERSIONS }}
      helm_extra_args: "--timeout 600s"
